apiVersion: apps/v1
kind: Deployment
metadata:
  name: citus-worker-deployment
  namespace: citus-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: citus-worker-app
  template:
    metadata:
      labels:
        app: citus-worker-app
    spec:
      volumes:
        - name: cluster-config-volume-storage
          persistentVolumeClaim:
            claimName: cluster-config-volume-claim
      containers:
      - name: citus-worker
        image: kubemaster:443/kubeuser/citus-image:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: cluster-config-volume-storage
            mountPath: /etc/citus/cluster-nodes-data
        ports:
        - containerPort: 5432
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo Hello World"]
          preStop:
            exec:
              command: ["/bin/sh", "-c", "shutdown_script.sh"]
      imagePullSecrets:
        - name: regcred

