apiVersion: apps/v1
kind: Deployment
metadata:
  name: citus-worker-deployment
  namespace: citus-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: citus-worker-app
  template:
    metadata:
      labels:
        app: citus-worker-app
    spec:
      containers:
      - name: citus-worker
        image: kubemaster:443/kubeuser/citus-image:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
      imagePullSecrets:
        - name: regcred

