apiVersion: apps/v1
kind: Deployment
metadata:
  name: citus-master-deployment
  namespace: citus-cluster
spec:
  replicas: 1
  volumes:
    - name: pg-workers-conf-vol
      nfs:
        server: kubemaster
        path: /srv/citus-cluster/cluster-nodes-data
  selector:
    matchLabels:
      app: citus-master-app
  template:
    metadata:
      labels:
        app: citus-master-app
    spec:
      containers:
      - name: citus-master
        image: kubemaster:443/kubeuser/citus-image:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: pg-workers-conf-vol
            mountPath: /etc/citus/cluster-nodes-data
      - name: citus-watcher
        image: kubemaster:443/kubeuser/citus-watcher:v1
        imagePullPolicy: Always
        volumeMounts:
          - name: pg-workers-conf-vol
            mountPath: /etc/citus/cluster-nodes-data
      imagePullSecrets:
      - name: regcred

