apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-workers-conf-vol
  namespace: citus-cluster
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: kubemaster
    path: "/srv/citus-cluster/cluster-nodes-data/"

