apiVersion: v1
kind: Service
metadata:
  name: citus-maembership
  namespace: citus-cluster
spec:
  selector:
    app: citus-master-app
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: NodePort

