apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: citus-master-sset
  namespace: citus-cluster
spec:
  serviceName: citus-master-service
  selector:
    matchLabels:
      app: citus-master-app
  replicas: 1 
  template:
    metadata:
      labels:
        app: citus-master-app
    spec:
      containers:
      - name: citus-master
        image: kubemaster:443/kubeuser/citus-image:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5432  
      - name: citus-k8s-sentinel
        image: kubemaster:443/kubeuser/citus-k8s-sentinel-image:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 1883
      imagePullSecrets:
        - name: regcred

