apiVersion: v1
kind: Service
metadata:
  name: citus-master-service
  namespace: citus-cluster
spec:
  selector:
    app: citus-master-app
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
  type: NodePort

